module.exports = {
  appId: '<%= appId %>',
  app: 'src/app',
  compileType: 'miniprogram',
  plugins: [],
  setting: {
		urlCheck: true,
		es6: false,
		enhance: false,
		postcss: false,
		preloadBackgroundData: false,
		minified: false,
		newFeature: false,
		coverView: true,
		nodeModules: false,
		autoAudits: false,
		showShadowRootInWxmlPanel: true,
		scopeDataCheck: false,
		uglifyFileName: false,
		checkInvalidKey: true,
		checkSiteMap: true,
		uploadWithSourceMap: true,
		compileHotReLoad: false,
		babelSetting: {
			ignore: [],
			disablePlugins: [],
			outputPath: "",
		},
		useIsolateContext: true,
		useCompilerModule: false,
		userConfirmedUseCompilerModuleSwitch: false,
	},
}
